### PR TITLE
fix(contract): init Reentrancy Guard

### PR DESCRIPTION
**Pull request by PierrickGT**
Issue: https://github.com/code-423n4/2021-06-pooltogether-findings/issues/60

### CODE REVIEW

**Comment by aodhgan** [comment]
What is the default behaviour of the reentrancy guard when its not initialized? Just default to 0?

ACK

**Comment by PierrickGT** [comment]
> What is the default behaviour of the reentrancy guard when its not initialized? Just default to 0?
> 
> ACK

Looking at the code, I feel like it would behave the same way than when initialized.

https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/master/contracts/security/ReentrancyGuardUpgradeable.sol#L44

By initializing it, `_status` is then equal to `_NOT_ENTERED`, so `1`. But without initializing it, `_status` would be equal to `0`, which wouldn't be a problem cause once the function called, it would still set `_status` to `_ENTERED` which is equal to `2`.

https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/91e0b106804c3f2ca7379577c680e4233e2be09c/contracts/security/ReentrancyGuardUpgradeable.sol#L59

**Comment by asselstine** [comment]
@PierrickGT @aodhgan. Likely gas costs.

**Comment by kamescg** [comment]
To my knowledge reverting back to 0 would have been cheaper, since no storage is required for reverting to the default.

https://eips.ethereum.org/EIPS/eip-2200

> If a contract with empty storage sets slot 0 to 1, then back to 0, it will be charged 20000 + 200 - 19800 = 400 gas.

> When original value is 0, we want to prove that:
> Case I: If the final value ends up still being 0, we want to charge 200 * N gases, because no disk write is needed.
> Case II: If the final value ends up being a non-zero value, we want to charge 20000 + 200 * (N-1) gas, because it requires writing this slot to disk.

**Comment by kamescg** [comment]
@PierrickGT @asselstinesSimilar to https://github.com/pooltogether/pooltogether-yearnv2-yield-source/pull/8#pullrequestreview-702571344 may want to remove `transferOwnership` from initialize to adhere with other PT contracts, even thought contract doesn't include additional function for setting config params?

**Pull request merged**
