### PR TITLE
fix(contract): depositToAave gas optimization

### PR DESCRIPTION
**Pull request by PierrickGT**
Issues: 
- https://github.com/code-423n4/2021-06-pooltogether-findings/issues/122
- https://github.com/code-423n4/2021-06-pooltogether-findings/issues/80

### CODE REVIEW

**Comment by aodhgan** [comment]
Oh so the gas savings with return values is only for external/public functions? Can we run the gas reporter on this?

**Comment by aodhgan** [comment]
ACK

**Comment by PierrickGT** [comment]
> Oh so the gas savings with return values is only for external/public functions? Can we run the gas reporter on this?

Yes, that's what we recommend in our doc: https://docs.pooltogether.com/contributing/smart-contract-guidelines#optimizations

On the main branch, `supplyTokenTo` consumes on average 157,718 units of gas and on this branch, it consumes on average 132,990 units of gas.

We should setup some CI integrations on our repos to see how gas consumption changes between PRs. Here is a setup guide: https://github.com/cgewecke/eth-gas-reporter/blob/master/docs/codechecks.md

**Comment by kamescg** [comment]
> Oh so the gas savings with return values is only for external/public functions? Can we run the gas reporter on this?

The gas savings is only for external/public functions which are called from another smart contract. There is no gas savings when calling from an EOA - in fact it might actually be a bit more for an EOA if returning a variable, instead of nothing.

The PR looks good to me.

**Pull request merged**
